# .streamlit/secrets.toml

[gsheets]
Sheet1 = "https://docs.google.com/spreadsheets/d/1gSmw9VYFViRO-FId4SN9wOHPMk6Yb8gi31ioKD1D1-A/edit#gid=0"
Sheet2 = "https://docs.google.com/spreadsheets/d/1VORW7PfvZZfEFejDBq3kRSXq7AeOEbajN8ExTSIpppM/edit?hl=id#gid=0"
Sheet3 ="https://docs.google.com/spreadsheets/d/1BMusjwh7BrXi5G1KiImJoQjVquxlEtgGSe53SHzEYzc/edit?hl=id#gid=0"
Sheet4 ="https://docs.google.com/spreadsheets/d/1BtAuaQ_9m1RKjuuGigd0uWSVn8ohHsFGMMNSAe0bUc8/edit?hl=id#gid=0"
Sheet5 ="https://docs.google.com/spreadsheets/d/1RoyB3GbeAR4ztyb7R4EtTS4DmQdkCRUvSqUcI1-1XcY/edit?hl=id#gid=0"
Sheet6 ="https://docs.google.com/spreadsheets/d/1mdeqlzif1Et5OaB16SToCy4FY4LqMavTLxplzxBU5Vg/edit?hl=id#gid=0"
Sheet7 ="https://docs.google.com/spreadsheets/d/1Ed8yHFfKcJNUsnXCGDM7LHnssEFTYWc_ytQCAOeEI4I/edit?hl=id#gid=0"
Sheet8 ="https://docs.google.com/spreadsheets/d/1XkSE7tW_9eakDynWdhgZ9RpGSl6e52ugXYyfRC6BHz4/edit?hl=id#gid=0"
Sheet9 ="https://docs.google.com/spreadsheets/d/1E_a-i65paEut9UpLQA5JSIgF-SsFokA7nPji2tVYd6U/edit?hl=id#gid=0"
Sheet10 ="https://docs.google.com/spreadsheets/d/1U50tkFx4u1IpFafIARMI_FrPhzlU4s9B6yfWfNKy42Q/edit?hl=id#gid=0"
Sheet11 ="https://docs.google.com/spreadsheets/d/1T2VTuI6GV0YVdMni6JloEBzU2X1RbU5QuI2EJ3RRFto/edit?hl=id#gid=0"
Sheet12 ="https://docs.google.com/spreadsheets/d/1Rtf24eT8fkMT37vzZd3Gk2KJU_Lx8FlaIAjrnXYTrJk/edit?hl=id#gid=0"